version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
      
  rabitmq:
    image: rabbitmq:3-management-alpine

volumes: 
    mongo_data:
